### PR TITLE
:bug: check if the username begins or ends with a period

### LINKED ISSUE #228: Dots should be limited in usernames
Good: `joel.hernandez`
Bad: `.`, `..` ...

### PR DESCRIPTION
**Pull request by tschwaerzl**
Check if the given username startswith or endswith a period.

Fixes #228

### CODE REVIEW

**Comment by Komposten** [comment]
I think this needs to be elaborated a bit more. Even after this change you can still have names like `_`, `_..._`, `a.....a`, etc.

**Comment by duichwer** [comment]
Maybe we want something like the following:

```
(?!\.)[a-zA-Z0-9]*([._]?[a-zA-Z0-9]+)*(?<!\.)
```

This enforces minimum one of `a-zA-Z0-9` and allows one of the special chars `[._]` in a row.

I'm not sure but with enforcing one character behind the special chars, the negative lookbehind could also be removed.
At the moment underscores aren't possible too at the end.

Another Option:
```
(?!\.)[a-zA-Z0-9]*([._]?[a-zA-Z0-9]+[._]?)*(?<!\.)
```

**Comment by lifenautjoe** [comment]
Hmm, should be alphanumeric and `_` and `.`, where those 2 characters can't be by themselves or the beginning nor end of the username

**Comment by duichwer** [comment]
I don't understand what you mean by "where those 2 characters can't be by themselves".
Do you mean, that we don't to allow the examples of @Komposten, but we allow something link `a.b.c_d_e`?

**Comment by Komposten** [comment]
Since we're checking a bounded string there is no reason to have lookaheads and lookbehinds. Better to define a concrete regex for the pattern we want, rather than trying to match what we don't want.

To that end something like this might suffice (not tested extensively, so might need some tweaking):
```
^[a-zA-Z0-9](?:[._]?[a-z-A-Z0-9])*$
```
Basically, always start with at least one alphanumeric character.
Follow that up with zero or more alphanumeric characters, each of which may be preceded by exactly one period or underscore.

Some examples (highlight = match):
image

**Comment by duichwer** [comment]
@Komposten thanks for the small fixes to my proposed regex. :)
@lifenautjoe how will we handle usernames that exist that aren't allowed with the new check anymore? I also found a username with a *é*, which isn't allowed.

**Pull request closed without merging**
