### PR TITLE
Bugfix/406 Add email address formatting for certain providers

### PR DESCRIPTION
**Pull request by javabudd**
Certain providers like Gmail ignore dots in addresses, allowing multiple accounts to be created using the same address. This PR addresses this issue by stripping out dots if the provider is one that ignores them, referencing https://github.com/OpenbookOrg/openbook-api/issues/406

### CODE REVIEW

**Comment by lifenautjoe** [comment]
Looks good, we need to do a bit more than this though as people can change their emails. Perhaps can be added as a formatter to the email field, so it always gets formatted?

**Comment by javabudd** [comment]
Sounds good to me. I’ll need to familiarize myself with formatters but I’ll update this PR with changes as soon as I can

**Comment by duichwer** [comment]
Besides the dots for gmail, would it be helpful to check if gmail addresses with the same values before the first + sign should be considered the same email, since they share the same main address?
 (see https://stackoverflow.com/questions/14865869/do-all-email-providers-ignore-periods-in-front-of)

However, the part after the plus sign should not be removed from the email, as there may be some users who use this to keep their inbox clean.

In my experience, "\*@gmail.com" and "\*@googlemail.com" are the same email address.
Then only one account should be possible?

**Comment by javabudd** [comment]
@duichwer You are correct about the gmail vs googlemail assumption, that needs to be factored into this as well.

`+` signs should also be formatted for ALL providers, however it might make more sense to just validate the email string and prevent + signs, up for debate.

**Pull request closed without merging**
