### PR TITLE
Docker Compose support

### PR DESCRIPTION
**Pull request by javabudd**
I have added Docker Compose support for easy development environments.

The `Dockerfile` builds out any system packages that are needed by the openbook API and the `entrypoint.sh` runs pipenv installs, migrations, media collection, and serves the webserver.

Webserver traffic is then served to a static IP on 172.16.16.1.

The Docker Compose settings may be overriden by copying `docker-compose.override.yml.dist` to `docker-compose.override.yml`.

You may enter the container and perform other operations, for example:
### execute into bash
```
docker-compose exec webserver bash
```

### CODE REVIEW

**Comment by hlrossato** [comment]
Hi @javabudd I'm trying to run the project with this configuration but I'm having a hard time. I'm running on a Macbook and the Docker runs but when accessing that IP address, it's timing out. Any tips that might help? Thanks

**Comment by javabudd** [comment]
Try copying docker-compose.override.yml.dist to docker-compose.override.yml and access it on `localhost`

**Comment by hlrossato** [comment]
I've tried that to no avail. I've managed to run the project using Docker with a configuration I used to use for other projects but when accessing localhost:8000 I'm seeing the Django yellow page. Is that supposed to happen? I want to believe that's not what should happen.

**Comment by javabudd** [comment]
@hlrossato are you using docker-compose as well?

**Comment by lifenautjoe** [comment]
Hi @hlrossato ! The django server indeed has no root view, its merely the APIs that the mobile app uses so sounds like its running!

**Pull request merged**
